const dorks = [
  'echo "******************* Specific Org search: *******************"',
  'echo ""',

  "password",
  "key",
  "api",
  "%22filename:vim_settings.xml%22",
  "%22Authorization:+Bearer%22",
  "%22Language:+PHP%22",
  "%22company.com%22+%22dev%22",
  "%22dev.company.com%22",
  "%22opensource.company.dev%22",
  "%22opensource.company.com%22",
  "%22company.com%22+API_key",
  "%22company.com%22+password",
  "%22api.company.com%22+authorization",

  'echo "******************* Sensitive Files search: *******************"',
  'echo ""',

  "path:sites+databases+password",
  "filename:manifest.xml",
  "filename:travis.yml",
  "filename:vim_settings.xml",
  "filename:database",
  "filename:secrets.yml+password",
  "filename:.esmtprc+password",
  "filename:passwd+path:etc",
  "filename:dbeaver-data-sources.xml",
  "filename:config.php+dbpasswd",
  "filename:.netrc+password",
  "filename:_netrc+password",
  "filename:hub+oauth_token",
  "filename:filezilla.xml+Pass",
  "filename:recentservers.xml+Pass",
  "filename:idea14.key",
  "filename:config+irc_pass",
  "filename:connections.xml",
  "filename:express.conf+path:.openshift",
  "filename:.pgpass",
  "filename:proftpdpasswd",
  "filename:ventrilo_srv.ini",
  "filename:settings.py+SECRET_KEY",
  "filename:master.key+path:config",
  "filename:deployment-config.json",
  "filename:.ftpconfig",
  "filename:.remote-sync.json",
  "filename:sftp.json+path:.vscode",
  "filename:WebServers.xml",
  "filename:jupyter_notebook_config.json",
  "filename:logins.json",
  "filename:CCCam.cfg",
  "filename:.bash_history",
  "filename:.cshrc",
  "filename:.history",
  "filename:.sh_history",
  "filename:sshd_config",
  "filename:dhcpd.conf",
  "filename:prod.exs+NOT+prod.secret.exs",
  "filename:prod.secret.exs",
  "filename:configuration.php+JConfig+password",
  "filename:config.php+pass",
  "filename:sftp-config.json",
  "filename:.npmrc+_auth",
  "filename:.dockercfg+auth",
  "filename:shadow+path:etc",
  "filename:id_rsa+or+filename:id_dsa",
  "filename:.tugboat+NOT+_tugboat",
  "filename:server.cfg+rcon+password",
  "filename:credentials+aws_access_key_id",
  "filename:.s3cfg",
  "filename:wp-config.php",
  "filename:.htpasswd",
  "filename:.env+DB_USERNAME+NOT+homestead",
  "filename:.env+MAIL_HOST=smtp.gmail.com",
  "filename:.git-credentials",
  "filename:.bashrc+password",
  "filename:.bashrc+mailchimp",
  "filename:.bash_profile+aws",
  "msg+nickserv+identify+filename:config",
  "rds.amazonaws.com+password",
  "SF_USERNAME+salesforce",
  "xoxp+OR+xoxb",
  ".mlab.com+password",

  'echo "******************* Specific Language based search: *******************"',
  'echo ""',

  "language:python+username",
  "language:php+username",
  "language:sql+username",
  "language:html+password",
  "language:perl+password",
  "language:shell+username",
  "language:java+api",
  "PT_TOKEN+language:bash",
  "HOMEBREW_GITHUB_API_TOKEN+language:shell",
  "shodan_api_key+language:python",
  "shodan_api_key+language:shell",
  "shodan_api_key+language:json",
  "shodan_api_key+language:ruby",
  "HEROKU_API_KEY+language:shell",
  "HEROKU_API_KEY+language:json",

  'echo "******************* API keys, Token & Hard-Coded Password search: *******************"',
  'echo ""',

  "SecretKey+/+Secret_Key+/+Secrect_key+/+skey",
  "privatekey+/+private_key+/+pkey",
  "user_secret+/+userSecret",
  "admin_passwd+/+adminpasswd+/+adminPass+etc",
  "%22api+keys%22",
  "authorization_bearer:",
  "oauth",
  "auth",
  "authentication",
  "client_secret",
  "api_token:",
  "%22api+token%22",
  "client_id",
  "password",
  "user_password",
  "user_pass",
  "passcode",
  "secret",
  "password+hash",
  "OTP",
  "user+auth",
  "JEKYLL_GITHUB_TOKEN",

  'echo "******************* Username search:*******************"',
  'echo ""',
  'echo "... NEEDS CORRECTION ..."',

  "(user:admin)",
  "org:name+(org:google+type:users)",
  "in:login+(<username>+in:login)",
  "in:name+(<username>+in:name)",
  "fullname:firstname+lastname+(fullname:<name>+<surname>)",
  "in:email+(data+in:email)",

  'echo "******************* GitHub Dorks for Finding Information using Dates: *******************"',
  'echo ""',

  "created:<2012–04–05",
  "created:>=2011–06–12",
  "created:2016–02–07+location:iceland",
  "created:2011–04–06..2013–01–14+<user>+in:username",

  'echo "******************* Extension based search: *******************"',
  'echo ""',

  "extension:pem+private",
  "extension:ppk+private",
  "extension:sql+mysql+dump",
  "extension:sql+mysql+dump+password",
  "extension:json+api.forecast.io",
  "extension:json+mongolab.com",
  "extension:yaml+mongolab.com",
  "extension:json+googleusercontent+client_secret",
  "extension:avastlic+%22support.avast.com%22",
  "[WFClient]+Password=+extension:ica",
  "jsforce+extension:js+conn.login",
];
