#!/bin/sh

# USE:
# ====   
#	Script Available At /Desktop/My Scripts/GitHubDorking.sh			
#	+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#	download the script
#	chmod +x GitHubDorking.sh
#	bash ./GitHubDorking.sh NameOfCompanyOrUser

#	Paste those generated links in your browser and voila :)	
#	+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo ""
echo "******************* Github Dork Links (must be logged into GitHub) *******************"
echo ""
echo "******************* ... Starting GitHub Recon ... *******************"
echo ""
echo "******************* Specific Org search: *******************"
echo ""

echo "    user:\"$1\" password"
echo "https://github.com/search?q=user:%22$1%22+password&type=Code"
echo ""
echo "    user:\"$1\" key"
echo "https://github.com/search?q=user:%22$1%22+key&type=Code"
echo ""
echo "    user:\"$1\" api"
echo "https://github.com/search?q=user:%22$1%22+api&type=Code"
echo ""
echo "    user:\"$1\" %22filename:vim_settings.xml%22"
echo "https://github.com/search?q=user:%22$1%22+%22filename:vim_settings.xml%22&type=Code"
echo ""
echo "    user:\"$1\" %22Authorization:+Bearer%22"
echo "https://github.com/search?q=user:%22$1%22+%22Authorization:+Bearer%22&type=Code"
echo ""
echo "    user:\"$1\" %22Language:+PHP%22"
echo "https://github.com/search?q=user:%22$1%22+%22Language:+PHP%22&type=Code"
echo ""
echo "    user:\"$1\" %22company.com%22+%22dev%22"
echo "https://github.com/search?q=user:%22$1%22+%22$1.com%22+%22dev%22&type=Code"
echo ""
echo "    user:\"$1\" %22dev.company.com%22"
echo "https://github.com/search?q=user:%22$1%22+%22dev.$1.com%22&type=Code"
echo ""
echo "    user:\"$1\" %22opensource.company.dev%22"
echo "https://github.com/search?q=user:%22$1%22+%22opensource.$1.dev%22&type=Code"
echo ""
echo "    user:\"$1\" %22opensource.company.com%22"
echo "https://github.com/search?q=user:%22$1%22+%22opensource.$1.com%22&type=Code"
echo ""
echo "    user:\"$1\" %22company.com%22+API_key"
echo "https://github.com/search?q=user:%22$1%22+%22$1.com%22+API_key&type=Code"
echo ""
echo "    user:\"$1\" %22company.com%22+password"
echo "https://github.com/search?q=user:%22$1%22+%22$1.com%22+password&type=Code"
echo ""
echo "    user:\"$1\" %22api.company.com%22+authorization"
echo "https://github.com/search?q=user:%22$1%22+%22api.$1.com%22+authorization&type=Code"
echo ""

echo "******************* Sensitive Files search: *******************"
echo ""

echo " user:\"$1\" path:sites+databases+password"
echo "https://github.com/search?q=user:%22$1%22+path:sites+databases+password&type=Code"
echo ""
echo " user:\"$1\" filename:manifest.xml"
echo "https://github.com/search?q=user:%22$1%22+filename:manifest.xml&type=Code"
echo ""
echo " user:\"$1\" filename:travis.yml"
echo "https://github.com/search?q=user:%22$1%22+filename:travis.yml&type=Code"
echo ""
echo " user:\"$1\" filename:vim_settings.xml"
echo "https://github.com/search?q=user:%22$1%22+filename:vim_settings.xml&type=Code"
echo ""
echo " user:\"$1\" filename:database"
echo "https://github.com/search?q=user:%22$1%22+filename:database&type=Code"
echo ""
echo " user:\"$1\" filename:secrets.yml+password"
echo "https://github.com/search?q=user:%22$1%22+filename:secrets.yml+password&type=Code"
echo ""
echo " user:\"$1\" filename:.esmtprc+password"
echo "https://github.com/search?q=user:%22$1%22+filename:.esmtprc+password&type=Code"
echo ""
echo " user:\"$1\" filename:passwd+path:etc"
echo "https://github.com/search?q=user:%22$1%22+filename:passwd+path:etc&type=Code"
echo ""
echo " user:\"$1\" filename:dbeaver-data-sources.xml"
echo "https://github.com/search?q=user:%22$1%22+filename:dbeaver-data-sources.xml&type=Code"
echo ""
echo " user:\"$1\" filename:config.php+dbpasswd"
echo "https://github.com/search?q=user:%22$1%22+filename:config.php+dbpasswd&type=Code"
echo ""
echo " user:\"$1\" filename:.netrc+password"
echo "https://github.com/search?q=user:%22$1%22+filename:.netrc+password&type=Code"
echo ""
echo " user:\"$1\" filename:_netrc+password"
echo "https://github.com/search?q=user:%22$1%22+filename:_netrc+password&type=Code"
echo ""
echo " user:\"$1\" filename:hub+oauth_token"
echo "https://github.com/search?q=user:%22$1%22+filename:hub+oauth_token&type=Code"
echo ""
echo " user:\"$1\" filename:filezilla.xml+Pass"
echo "https://github.com/search?q=user:%22$1%22+filename:filezilla.xml+Pass&type=Code"
echo ""
echo " user:\"$1\" filename:recentservers.xml+Pass"
echo "https://github.com/search?q=user:%22$1%22+filename:recentservers.xml+Pass&type=Code"
echo ""
echo " user:\"$1\" filename:idea14.key"
echo "https://github.com/search?q=user:%22$1%22+filename:idea14.key&type=Code"
echo ""
echo " user:\"$1\" filename:config+irc_pass"
echo "https://github.com/search?q=user:%22$1%22+filename:config+irc_pass&type=Code"
echo ""
echo " user:\"$1\" filename:connections.xml"
echo "https://github.com/search?q=user:%22$1%22+filename:connections.xml&type=Code"
echo ""
echo " user:\"$1\" filename:express.conf+path:.openshift"
echo "https://github.com/search?q=user:%22$1%22+filename:express.conf+path:.openshift&type=Code"
echo ""
echo " user:\"$1\" filename:.pgpass"
echo "https://github.com/search?q=user:%22$1%22+filename:.pgpass&type=Code"
echo ""
echo " user:\"$1\" filename:proftpdpasswd"
echo "https://github.com/search?q=user:%22$1%22+filename:proftpdpasswd&type=Code"
echo ""
echo " user:\"$1\" filename:ventrilo_srv.ini"
echo "https://github.com/search?q=user:%22$1%22+filename:ventrilo_srv.ini&type=Code"
echo ""
echo " user:\"$1\" filename:settings.py+SECRET_KEY"
echo "https://github.com/search?q=user:%22$1%22+filename:settings.py+SECRET_KEY&type=Code"
echo ""
echo " user:\"$1\" filename:master.key+path:config"
echo "https://github.com/search?q=user:%22$1%22+filename:master.key+path:config&type=Code"
echo ""
echo " user:\"$1\" filename:deployment-config.json"
echo "https://github.com/search?q=user:%22$1%22+filename:deployment-config.json&type=Code"
echo ""
echo " user:\"$1\" filename:.ftpconfig"
echo "https://github.com/search?q=user:%22$1%22+filename:.ftpconfig&type=Code"
echo ""
echo " user:\"$1\" filename:.remote-sync.json"
echo "https://github.com/search?q=user:%22$1%22+filename:.remote-sync.json&type=Code"
echo ""
echo " user:\"$1\" filename:sftp.json+path:.vscode"
echo "https://github.com/search?q=user:%22$1%22+filename:sftp.json+path:.vscode&type=Code"
echo ""
echo " user:\"$1\" filename:WebServers.xml"
echo "https://github.com/search?q=user:%22$1%22+filename:WebServers.xml&type=Code"
echo ""
echo " user:\"$1\" filename:jupyter_notebook_config.json"
echo "https://github.com/search?q=user:%22$1%22+filename:jupyter_notebook_config.json&type=Code"
echo ""
echo " user:\"$1\" filename:logins.json"
echo "https://github.com/search?q=user:%22$1%22+filename:logins.json&type=Code"
echo ""
echo " user:\"$1\" filename:CCCam.cfg"
echo "https://github.com/search?q=user:%22$1%22+filename:CCCam.cfg&type=Code"
echo ""
echo " user:\"$1\" filename:.bash_history"
echo "https://github.com/search?q=user:%22$1%22+filename:.bash_history&type=Code"
echo ""
echo " user:\"$1\" filename:.cshrc"
echo "https://github.com/search?q=user:%22$1%22+filename:.cshrc&type=Code"
echo ""
echo " user:\"$1\" filename:.history"
echo "https://github.com/search?q=user:%22$1%22+filename:.history&type=Code"
echo ""
echo " user:\"$1\" filename:.sh_history"
echo "https://github.com/search?q=user:%22$1%22+filename:.sh_history&type=Code"
echo ""
echo " user:\"$1\" filename:sshd_config"
echo "https://github.com/search?q=user:%22$1%22+filename:sshd_config&type=Code"
echo ""
echo " user:\"$1\" filename:dhcpd.conf"
echo "https://github.com/search?q=user:%22$1%22+filename:dhcpd.conf&type=Code"
echo ""
echo " user:\"$1\" filename:prod.exs+NOT+prod.secret.exs"
echo "https://github.com/search?q=user:%22$1%22+filename:prod.exs+NOT+prod.secret.exs&type=Code"
echo ""
echo " user:\"$1\" filename:prod.secret.exs"
echo "https://github.com/search?q=user:%22$1%22+filename:prod.secret.exs&type=Code"
echo ""
echo " user:\"$1\" filename:configuration.php+JConfig+password"
echo "https://github.com/search?q=user:%22$1%22+filename:configuration.php+JConfig+password&type=Code"
echo ""
echo " user:\"$1\" filename:config.php+pass"
echo "https://github.com/search?q=user:%22$1%22+filename:config.php+pass&type=Code"
echo ""
echo " user:\"$1\" filename:sftp-config.json"
echo "https://github.com/search?q=user:%22$1%22+filename:sftp-config.json&type=Code"
echo ""
echo " user:\"$1\" filename:.npmrc+_auth"
echo "https://github.com/search?q=user:%22$1%22+filename:.npmrc+_auth&type=Code"
echo ""
echo " user:\"$1\" filename:.dockercfg+auth"
echo "https://github.com/search?q=user:%22$1%22+filename:.dockercfg+auth&type=Code"
echo ""
echo " user:\"$1\" filename:shadow+path:etc"
echo "https://github.com/search?q=user:%22$1%22+filename:shadow+path:etc&type=Code"
echo ""
echo " user:\"$1\" filename:id_rsa+or+filename:id_dsa"
echo "https://github.com/search?q=user:%22$1%22+filename:id_rsa+or+filename:id_dsa&type=Code"
echo ""
echo " user:\"$1\" filename:.tugboat+NOT+_tugboat"
echo "https://github.com/search?q=user:%22$1%22+filename:.tugboat+NOT+_tugboat&type=Code"
echo ""
echo " user:\"$1\" filename:server.cfg+rcon+password"
echo "https://github.com/search?q=user:%22$1%22+filename:server.cfg+rcon+password&type=Code"
echo ""
echo " user:\"$1\" filename:credentials+aws_access_key_id"
echo "https://github.com/search?q=user:%22$1%22+filename:credentials+aws_access_key_id&type=Code"
echo ""
echo " user:\"$1\" filename:.s3cfg"
echo "https://github.com/search?q=user:%22$1%22+filename:.s3cfg&type=Code"
echo ""
echo " user:\"$1\" filename:wp-config.php"
echo "https://github.com/search?q=user:%22$1%22+filename:wp-config.php&type=Code"
echo ""
echo " user:\"$1\" filename:.htpasswd"
echo "https://github.com/search?q=user:%22$1%22+filename:.htpasswd&type=Code"
echo ""
echo " user:\"$1\" filename:.env+DB_USERNAME+NOT+homestead"
echo "https://github.com/search?q=user:%22$1%22+filename:.env+DB_USERNAME+NOT+homestead&type=Code"
echo ""
echo " user:\"$1\" filename:.env+MAIL_HOST=smtp.gmail.com"
echo "https://github.com/search?q=user:%22$1%22+filename:.env+MAIL_HOST=smtp.gmail.com&type=Code"
echo ""
echo " user:\"$1\" filename:.git-credentials"
echo "https://github.com/search?q=user:%22$1%22+filename:.git-credentials&type=Code"
echo ""
echo " user:\"$1\" filename:.bashrc+password"
echo "https://github.com/search?q=user:%22$1%22+filename:.bashrc+password&type=Code"
echo ""
echo " user:\"$1\" filename:.bashrc+mailchimp"
echo "https://github.com/search?q=user:%22$1%22+filename:.bashrc+mailchimp&type=Code"
echo ""
echo " user:\"$1\" filename:.bash_profile+aws"
echo "https://github.com/search?q=user:%22$1%22+filename:.bash_profile+aws&type=Code"
echo ""
echo " user:\"$1\" msg+nickserv+identify+filename:config"
echo "https://github.com/search?q=user:%22$1%22+msg+nickserv+identify+filename:config&type=Code"
echo ""
echo " user:\"$1\" rds.amazonaws.com+password"
echo "https://github.com/search?q=user:%22$1%22+rds.amazonaws.com+password&type=Code"
echo ""
echo " user:\"$1\" SF_USERNAME+salesforce"
echo "https://github.com/search?q=user:%22$1%22+SF_USERNAME+salesforce&type=Code"
echo ""
echo " user:\"$1\" xoxp+OR+xoxb"
echo "https://github.com/search?q=user:%22$1%22+xoxp+OR+xoxb&type=Code"
echo ""
echo " user:\"$1\" .mlab.com+password"
echo "https://github.com/search?q=user:%22$1%22+.mlab.com+password&type=Code"
echo ""

echo "******************* Specific Language based search: *******************"
echo ""

echo " user:\"$1\" language:python+username"
echo "https://github.com/search?q=user:%22$1%22+language:python+username&type=Code"
echo ""
echo " user:\"$1\" language:php+username"
echo "https://github.com/search?q=user:%22$1%22+language:php+username&type=Code"
echo ""
echo " user:\"$1\" language:sql+username"
echo "https://github.com/search?q=user:%22$1%22+language:sql+username&type=Code"
echo ""
echo " user:\"$1\" language:html+password"
echo "https://github.com/search?q=user:%22$1%22+language:html+password&type=Code"
echo ""
echo " user:\"$1\" language:perl+password"
echo "https://github.com/search?q=user:%22$1%22+language:perl+password&type=Code"
echo ""
echo " user:\"$1\" language:shell+username"
echo "https://github.com/search?q=user:%22$1%22+language:shell+username&type=Code"
echo ""
echo " user:\"$1\" language:java+api"
echo "https://github.com/search?q=user:%22$1%22+language:java+api&type=Code"
echo ""
echo " user:\"$1\" PT_TOKEN+language:bash"
echo "https://github.com/search?q=user:%22$1%22+PT_TOKEN+language:bash&type=Code"
echo ""
echo " user:\"$1\" HOMEBREW_GITHUB_API_TOKEN+language:shell"
echo "https://github.com/search?q=user:%22$1%22+HOMEBREW_GITHUB_API_TOKEN+language:shell&type=Code"
echo ""
echo " user:\"$1\" shodan_api_key+language:python"
echo "https://github.com/search?q=user:%22$1%22+shodan_api_key+language:python&type=Code"
echo ""
echo " user:\"$1\" shodan_api_key+language:shell"
echo "https://github.com/search?q=user:%22$1%22+shodan_api_key+language:shell&type=Code"
echo ""
echo " user:\"$1\" shodan_api_key+language:json"
echo "https://github.com/search?q=user:%22$1%22+shodan_api_key+language:json&type=Code"
echo ""
echo " user:\"$1\" shodan_api_key+language:ruby"
echo "https://github.com/search?q=user:%22$1%22+shodan_api_key+language:ruby&type=Code"
echo ""
echo " user:\"$1\" HEROKU_API_KEY+language:shell"
echo "https://github.com/search?q=user:%22$1%22+HEROKU_API_KEY+language:shell&type=Code"
echo ""
echo " user:\"$1\" HEROKU_API_KEY+language:json"
echo "https://github.com/search?q=user:%22$1%22+HEROKU_API_KEY+language:json&type=Code"
echo ""

echo "******************* API keys, Token & Hard-Coded Password search: *******************"
echo ""

echo " user:\"$1\" SecretKey+/+Secret_Key+/+Secrect_key+/+skey"
echo "https://github.com/search?q=user:%22$1%22+SecretKey+/+Secret_Key+/+Secrect_key+/+skey&type=Code"
echo ""
echo " user:\"$1\" privatekey+/+private_key+/+pkey"
echo "https://github.com/search?q=user:%22$1%22+privatekey+/+private_key+/+pkey&type=Code"
echo ""
echo " user:\"$1\" user_secret+/+userSecret"
echo "https://github.com/search?q=user:%22$1%22+user_secret+/+userSecret&type=Code"
echo ""
echo " user:\"$1\" admin_passwd+/+adminpasswd+/+adminPass+etc"
echo "https://github.com/search?q=user:%22$1%22+admin_passwd+/+adminpasswd+/+adminPass+etc&type=Code"
echo ""
echo " user:\"$1\" %22api+keys%22"
echo "https://github.com/search?q=user:%22$1%22+%22api+keys%22&type=Code"
echo ""
echo " user:\"$1\" authorization_bearer:"
echo "https://github.com/search?q=user:%22$1%22+authorization_bearer:&type=Code"
echo ""
echo " user:\"$1\" oauth"
echo "https://github.com/search?q=user:%22$1%22+oauth&type=Code"
echo ""
echo " user:\"$1\" auth"
echo "https://github.com/search?q=user:%22$1%22+auth&type=Code"
echo ""
echo " user:\"$1\" authentication"
echo "https://github.com/search?q=user:%22$1%22+authentication&type=Code"
echo ""
echo " user:\"$1\" client_secret"
echo "https://github.com/search?q=user:%22$1%22+client_secret&type=Code"
echo ""
echo " user:\"$1\" api_token:"
echo "https://github.com/search?q=user:%22$1%22+api_token:&type=Code"
echo ""
echo " user:\"$1\" %22api+token%22"
echo "https://github.com/search?q=user:%22$1%22+%22api+token%22&type=Code"
echo ""
echo " user:\"$1\" client_id"
echo "https://github.com/search?q=user:%22$1%22+client_id&type=Code"
echo ""
echo " user:\"$1\" password"
echo "https://github.com/search?q=user:%22$1%22+password&type=Code"
echo ""
echo " user:\"$1\" user_password"
echo "https://github.com/search?q=user:%22$1%22+user_password&type=Code"
echo ""
echo " user:\"$1\" user_pass"
echo "https://github.com/search?q=user:%22$1%22+user_pass&type=Code"
echo ""
echo " user:\"$1\" passcode"
echo "https://github.com/search?q=user:%22$1%22+passcode&type=Code"
echo ""
echo " user:\"$1\" secret"
echo "https://github.com/search?q=user:%22$1%22+secret&type=Code"
echo ""
echo " user:\"$1\" password+hash"
echo "https://github.com/search?q=user:%22$1%22+password+hash&type=Code"
echo ""
echo " user:\"$1\" OTP"
echo "https://github.com/search?q=user:%22$1%22+OTP&type=Code"
echo ""
echo " user:\"$1\" user+auth"
echo "https://github.com/search?q=user:%22$1%22+user+auth&type=Code"
echo ""
echo " user:\"$1\" JEKYLL_GITHUB_TOKEN"
echo "https://github.com/search?q=user:%22$1%22+JEKYLL_GITHUB_TOKEN&type=Code"
echo ""

echo "******************* Username search: *******************"
echo ""
echo "... NEEDS CORRECTION ..."

echo " user:\"$1\" (user:admin)"
echo "https://github.com/search?q=user:%22$1%22+(user:admin)&type=Code"
echo ""
echo " org:\"$1\" (org:google+type:users)"
echo "https://github.com/search?q=org:%22$1%22+(org:google+type:users)&type=Code"
echo ""
echo " in:login+($1+in:login)"
echo "https://github.com/search?q=in:login+($1+in:login)&type=Code"
echo ""
echo " in:name+($1+in:name)"
echo "https://github.com/search?q=in:name+($1+in:name)&type=Code"
echo ""
echo " fullname:firstname+lastname+(fullname:$1+<surname>)"
echo "https://github.com/search?q=fullname:firstname+lastname+(fullname:$1+surname)&type=Code"
echo ""
echo " user:\"$1\" in:email+(data+in:email)"
echo "https://github.com/search?q=user:%22$1%22+in:email+(data+in:email)&type=Code"
echo ""

echo "******************* GitHub Dorks for Finding Information using Dates: *******************"
echo ""

echo " user:\"$1\" created:<2012–04–05"
echo "https://github.com/search?q=user:%22$1%22+created:<2012–04–05&type=Code"
echo ""
echo " user:\"$1\" created:>=2011–06–12"
echo "https://github.com/search?q=user:%22$1%22+created:>=2011–06–12&type=Code"
echo ""
echo " user:\"$1\" created:2016–02–07+location:iceland"
echo "https://github.com/search?q=user:%22$1%22+created:2016–02–07+location:iceland&type=Code"
echo ""
echo " created:2011–04–06..2013–01–14+$1+in:username"
echo "https://github.com/search?q=user:%22$1%22+created:2011–04–06..2013–01–14+$1+in:username&type=Code"
echo ""

echo "******************* Extension based search: *******************"
echo ""

echo " user:\"$1\" extension:pem+private"
echo "https://github.com/search?q=user:%22$1%22+extension:pem+private&type=Code"
echo ""
echo " user:\"$1\" extension:ppk+private"
echo "https://github.com/search?q=user:%22$1%22+extension:ppk+private&type=Code"
echo ""
echo " user:\"$1\" extension:sql+mysql+dump"
echo "https://github.com/search?q=user:%22$1%22+extension:sql+mysql+dump&type=Code"
echo ""
echo " user:\"$1\" extension:sql+mysql+dump+password"
echo "https://github.com/search?q=user:%22$1%22+extension:sql+mysql+dump+password&type=Code"
echo ""
echo " user:\"$1\" extension:json+api.forecast.io"
echo "https://github.com/search?q=user:%22$1%22+extension:json+api.forecast.io&type=Code"
echo ""
echo " user:\"$1\" extension:json+mongolab.com"
echo "https://github.com/search?q=user:%22$1%22+extension:json+mongolab.com&type=Code"
echo ""
echo " user:\"$1\" extension:yaml+mongolab.com"
echo "https://github.com/search?q=user:%22$1%22+extension:yaml+mongolab.com&type=Code"
echo ""
echo " user:\"$1\" extension:json+googleusercontent+client_secret"
echo "https://github.com/search?q=user:%22$1%22+extension:json+googleusercontent+client_secret&type=Code"
echo ""
echo " user:\"$1\" extension:avastlic+%22support.avast.com%22"
echo "https://github.com/search?q=user:%22$1%22+extension:avastlic+%22support.avast.com%22&type=Code"
echo ""
echo " user:\"$1\" [WFClient]+Password=+extension:ica"
echo "https://github.com/search?q=user:%22$1%22+[WFClient]+Password=+extension:ica&type=Code"
echo ""
echo " user:\"$1\" jsforce+extension:js+conn.login"
echo "https://github.com/search?q=user:%22$1%22+jsforce+extension:js+conn.login&type=Code"
echo ""

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# RUN
# chmod +x GitHubDorking.sh
# bash ./GitHubDorking.sh NameOfCompanyOrUser

# Paste those generated links in your browser and voila money :)	
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
